### ISSUE TITLE
 Found an unknown sqltype ...

### ISSUE THREAD

**Issue by adrianlmm** [mariuz/flamerobin#203]
In Firebird 4 32 bits this query throws the exception:

Error: *** IBPP::LogicException ***
Context: RowImpl::AllocVariables
Message: Found an unknown sqltype !

This query works fine in ISQL.

Flamerobin version:

FlameRobin 0.9.3 (git hash 78287cd4) Unicode
Database administration tool for Firebird RDBMS

This tool uses IBPP library version 2.5.2.1
wxWidgets library version 3.1.4

**Comment by arvanus** [comment]
You need to set compatibility mode inside firebird.conf

**Comment by arvanus** [comment]
at firebird.conf you find this:


# ----------------------------
# Engine currently provides a number of new datatypes unknown to legacy clients.
# In order to simplify use of old applications set this parameter to minor FB
# version datatype compatibility with which you need. Currently two values are
# supported: 3.0 & 2.5.
# More precise (including per-session) tuning is possible via SQL and DPB.
#
# Per-database configurable.
#
#    Type: string
#
#DataTypeCompatibility =
Just set 'DataTypeCompatibility ' to 2.5 or 3.0

**Comment by adrianlmm** [comment]
That worked. Thanks.
