### ISSUE TITLE
Separate the triggers in 2 nodes: "Triggers" and "Database Triggers"

### ISSUE THREAD

**Issue by luronumen** [mariuz/flamerobin#48]
Please separate the triggers in 2 nodes: "Triggers" for table triggers and "Database Triggers" for the database triggers (See RedExpert tool as reference):

![RedExpert](https://user-images.githubusercontent.com/8019466/89827006-728bd780-db2d-11ea-9a92-1c0c436618ff.PNG)

**Comment by arvanus** [comment]
Just my thoughts:
I liked this idea:
```
[-] Triggers
   [-] ALL Triggers
      CONN1_TR
      ...
   [+] Database Triggers
   [+] DDL Triggers
   [+] Table Triggers

```
Maybe I would just change the subfolder pattern, you don't need to reinforce that "All" , "Database", "DDL" and "Table" refers to triggers, they are already inside triggers, doesn't change a lot, but "less is more" ;) 
```
[-] Triggers
   [-] ALL
      CONN1_TR
      ...
   [+] Database
   [+] DDL
   [+] Table

```

I agree with `Rename FunctionSQLs for just Functions`, but maybe for now, keep like this because "Functions" where used for UDFs and this kind of changes goes easy for a bug/miss-renaming or something like that if you don't take care enough  

System Tables exists from along time, I disagree with removing it
... for now, it's it :)
Thanks for your effort helping Flamerobin

**Comment by Jdochoa** [comment]
Hi all

**- Hide System tables and System domains:** This is configurable in preferences database.
![imagen](https://user-images.githubusercontent.com/11672188/90996691-bf839b00-e57c-11ea-9faa-3cd35585a5fc.png)

**- Add Indexes node:**   It's a good idea, I'll work on it
**- Rename FunctionSQLs for just Functions:** I agree.
**- Put them in a SUB-tree folder:** I agree.
**- Rename Global temporary tables for just Global Temporaries:** I agree, i change it.
**- Rename Generators to Sequences:** I'm not sure. I'm think we should keep backward compatibility with FB and FR.

**Comment by luronumen** [comment]
Hi @PizzaProgram , @arvanus  and @Jdochoa 

Let's leave GENERATORS for now instead of SEQUENCES.
We think better about this change in the bug #54

For a better organization of the triggers we can do as PizzaProgram suggested:

[-] Triggers
        [+] Database
        [+] DDL
        [+] Table



Best Regards,
Luciano

**Comment by luronumen** [comment]
Retest result on [FlameRobin 0.9.3.8 Snapshot](https://github.com/mariuz/flamerobin/releases/tag/0.9.3.8): **Passed!**

Thank you very much for the fix!
